<a href="https://colab.research.google.com/github/FasikuChristian/QSAR-Modeling-Pipeline-for-Serine-Threonine-Kinase-1/blob/main/CDD_ML_Part_1_bioactivity_data.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

# **Computational Drug Discovery [Part 1] Download Bioactivity Data using *CHEMBL DATABASE*

Credits: Chanin Nantasenamat(Data Professor) for developing this pipeline

---

## **Installing libraries**

Install the ChEMBL web service package so that we can retrieve bioactivity data from the ChEMBL Database.

In [ ]:
! pip install chembl_webresource_client

Collecting chembl_webresource_client
  Downloading chembl_webresource_client-0.10.9-py3-none-any.whl.metadata (1.4 kB)
Requirement already satisfied: urllib3 in /usr/local/lib/python3.12/dist-packages (from chembl_webresource_client) (2.5.0)
Requirement already satisfied: requests>=2.18.4 in /usr/local/lib/python3.12/dist-packages (from chembl_webresource_client) (2.32.4)
Collecting requests-cache~=1.2 (from chembl_webresource_client)
  Downloading requests_cache-1.3.1-py3-none-any.whl.metadata (9.4 kB)
Requirement already satisfied: easydict in /usr/local/lib/python3.12/dist-packages (from chembl_webresource_client) (1.13)
Requirement already satisfied: charset_normalizer<4,>=2 in /usr/local/lib/python3.12/dist-packages (from requests>=2.18.4->chembl_webresource_client) (3.4.6)
Requirement already satisfied: idna<4,>=2.5 in /usr/local/lib/python3.12/dist-packages (from requests>=2.18.4->chembl_webresource_client) (3.11)
Requirement already satisfied: certifi>=2017.4.17 in /usr/local/lib/python3.12/dist-packages (from requests>=2.18.4->chembl_webresource_client) (2026.2.25)
Requirement already satisfied: attrs>=21.2 in /usr/local/lib/python3.12/dist-packages (from requests-cache~=1.2->chembl_webresource_client) (25.4.0)
Collecting cattrs>=22.2 (from requests-cache~=1.2->chembl_webresource_client)
  Downloading cattrs-26.1.0-py3-none-any.whl.metadata (8.5 kB)
Requirement already satisfied: platformdirs>=2.5 in /usr/local/lib/python3.12/dist-packages (from requests-cache~=1.2->chembl_webresource_client) (4.9.4)
Collecting url-normalize>=2.0 (from requests-cache~=1.2->chembl_webresource_client)
  Downloading url_normalize-2.2.1-py3-none-any.whl.metadata (5.6 kB)
Requirement already satisfied: typing-extensions>=4.14.0 in /usr/local/lib/python3.12/dist-packages (from cattrs>=22.2->requests-cache~=1.2->chembl_webresource_client) (4.15.0)
Downloading chembl_webresource_client-0.10.9-py3-none-any.whl (55 kB)
   ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 55.2/55.2 kB 4.7 MB/s eta 0:00:00
Downloading requests_cache-1.3.1-py3-none-any.whl (70 kB)
   ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 70.2/70.2 kB 5.6 MB/s eta 0:00:00
Downloading cattrs-26.1.0-py3-none-any.whl (73 kB)
   ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 73.1/73.1 kB 6.5 MB/s eta 0:00:00
Downloading url_normalize-2.2.1-py3-none-any.whl (14 kB)
Installing collected packages: url-normalize, cattrs, requests-cache, chembl_webresource_client
Successfully installed cattrs-26.1.0 chembl_webresource_client-0.10.9 requests-cache-1.3.1 url-normalize-2.2.1

## **Importing libraries**

In [ ]:
# Import necessary libraries
import pandas as pd
from chembl_webresource_client.new_client import new_client

## **Search for Target protein**

### **Target search for AKT1**

In [ ]:
# Target search for AKT1
target = new_client.target
target_query = target.search('AKT Serine/Threonine Kinase 1')
targets = pd.DataFrame.from_dict(target_query)
targets

,cross_references,organism,pref_name,score,species_group_flag,target_chembl_id,target_components,target_type,tax_id
0,[],Homo sapiens,Serine/threonine-protein kinase AKT,29.0,False,CHEMBL2111353,"[{'accession': 'P31751', 'component_descriptio...",PROTEIN FAMILY,9606.0
1,[],Mus musculus,RAC-beta serine/threonine-protein kinase,28.0,False,CHEMBL5382,"[{'accession': 'Q60823', 'component_descriptio...",SINGLE PROTEIN,10090.0
2,[],Mus musculus,RAC-alpha serine/threonine-protein kinase,28.0,False,CHEMBL5859,"[{'accession': 'P31750', 'component_descriptio...",SINGLE PROTEIN,10090.0
3,[],Homo sapiens,Serine/threonine-protein kinase Rac alpha/beta,28.0,False,CHEMBL4106175,"[{'accession': 'P31751', 'component_descriptio...",PROTEIN FAMILY,9606.0
4,[],Homo sapiens,RAC-beta serine/threonine-protein kinase,27.0,False,CHEMBL2431,"[{'accession': 'P31751', 'component_descriptio...",SINGLE PROTEIN,9606.0
...,...,...,...,...,...,...,...,...,...
5870,[],Severe acute respiratory syndrome coronavirus 2,Replicase polyprotein 1ab,0.0,False,CHEMBL4523582,"[{'accession': 'P0DTD1', 'component_descriptio...",SINGLE PROTEIN,2697049.0
5871,[],Homo sapiens,Protein cereblon/Tubulin beta,0.0,False,CHEMBL6066847,"[{'accession': 'P68371', 'component_descriptio...",PROTEIN-PROTEIN INTERACTION,9606.0
5872,[],Mus musculus,RNA polymerase II,0.0,False,CHEMBL6066856,"[{'accession': 'P08775', 'component_descriptio...",PROTEIN COMPLEX,10090.0
5873,[],Severe acute respiratory syndrome coronavirus 2,Protein cereblon-SARS-Cov-2 polyprotein,0.0,False,CHEMBL6067603,"[{'accession': 'Q96SW2', 'component_descriptio...",PROTEIN-PROTEIN INTERACTION,2697049.0
5874,[],Severe acute respiratory syndrome coronavirus 2,von Hippel-Lindau disease tumor suppressor-SAR...,0.0,False,CHEMBL6067604,"[{'accession': 'P40337', 'component_descriptio...",PROTEIN-PROTEIN INTERACTION,2697049.0

In [ ]:
targets.head()

,cross_references,organism,pref_name,score,species_group_flag,target_chembl_id,target_components,target_type,tax_id
0,[],Homo sapiens,Serine/threonine-protein kinase AKT,29.0,False,CHEMBL2111353,"[{'accession': 'P31751', 'component_descriptio...",PROTEIN FAMILY,9606.0
1,[],Mus musculus,RAC-beta serine/threonine-protein kinase,28.0,False,CHEMBL5382,"[{'accession': 'Q60823', 'component_descriptio...",SINGLE PROTEIN,10090.0
2,[],Mus musculus,RAC-alpha serine/threonine-protein kinase,28.0,False,CHEMBL5859,"[{'accession': 'P31750', 'component_descriptio...",SINGLE PROTEIN,10090.0
3,[],Homo sapiens,Serine/threonine-protein kinase Rac alpha/beta,28.0,False,CHEMBL4106175,"[{'accession': 'P31751', 'component_descriptio...",PROTEIN FAMILY,9606.0
4,[],Homo sapiens,RAC-beta serine/threonine-protein kinase,27.0,False,CHEMBL2431,"[{'accession': 'P31751', 'component_descriptio...",SINGLE PROTEIN,9606.0

### **Select and retrieve bioactivity data for *AKT1* (fifth entry)**

We will assign the first entry (which corresponds to the target protein, *AKT1*) to the ***selected_target*** variable

In [ ]:
selected_target = targets.target_chembl_id[0]
selected_target

'CHEMBL2111353'

Here, we will retrieve only bioactivity data for *AKT1* (CHEMBL2111353) that are reported as IC$_{50}$ values in nM (nanomolar) unit.

In [ ]:
activity = new_client.activity
res = activity.filter(target_chembl_id=selected_target).filter(standard_type="IC50")

In [ ]:
df = pd.DataFrame.from_dict(res)

In [ ]:
df.head(3)

,action_type,activity_comment,activity_id,activity_properties,assay_chembl_id,assay_description,assay_type,assay_variant_accession,assay_variant_mutation,bao_endpoint,...,target_organism,target_pref_name,target_tax_id,text_value,toid,type,units,uo_units,upper_value,value
0,None,None,316960,[],CHEMBL766864,Inhibition of Protein kinase B (AKT) at ATP <Km,B,None,None,BAO_0000190,...,Homo sapiens,Serine/threonine-protein kinase AKT,9606,None,None,IC50,uM,UO_0000065,None,20.0
1,None,None,328362,[],CHEMBL766865,Inhibition of Protein kinase B (AKT) at ATP <Km,B,None,None,BAO_0000190,...,Homo sapiens,Serine/threonine-protein kinase AKT,9606,None,None,IC50,uM,UO_0000065,None,20.0
2,None,None,491918,[],CHEMBL709030,Inhibition of Akt phosphorylation in LoVo cells,F,None,None,BAO_0000190,...,Homo sapiens,Serine/threonine-protein kinase AKT,9606,None,None,IC50,nM,UO_0000065,None,1000.0

In [ ]:
df.standard_type.unique()

array(['IC50'], dtype=object)

Finally we will save the resulting bioactivity data to a CSV file **bioactivity_data.csv**.

In [ ]:
df.to_csv('bioactivity_data.csv', index=False)

## **Copying files to Google Drive**

Firstly, we need to mount the Google Drive into Colab so that we can have access to our Google adrive from within Colab.

In [ ]:
from google.colab import drive
drive.mount('/content/gdrive/', force_remount=True)

Mounted at /content/gdrive/

Next, we create a **data** folder in our **Colab Notebooks** folder on Google Drive.

In [ ]:
! mkdir "/content/gdrive/My Drive/Colab Notebooks/data2"

In [ ]:
! cp bioactivity_data.csv "/content/gdrive/My Drive/Colab Notebooks/data"

In [ ]:
! ls -l "/content/gdrive/My Drive/Colab Notebooks/data"

-rw------- 1 root root 122535 Mar 20 07:20 '/content/gdrive/My Drive/Colab Notebooks/data'

Let's see the CSV files that we have so far.

In [ ]:
! ls

bioactivity_data.csv  gdrive  sample_data

Taking a glimpse of the **bioactivity_data.csv** file that we've just created.

In [ ]:
! head bioactivity_data.csv

action_type,activity_comment,activity_id,activity_properties,assay_chembl_id,assay_description,assay_type,assay_variant_accession,assay_variant_mutation,bao_endpoint,bao_format,bao_label,canonical_smiles,data_validity_comment,data_validity_description,document_chembl_id,document_journal,document_year,ligand_efficiency,molecule_chembl_id,molecule_pref_name,parent_molecule_chembl_id,pchembl_value,potential_duplicate,qudt_units,record_id,relation,src_id,standard_flag,standard_relation,standard_text_value,standard_type,standard_units,standard_upper_value,standard_value,target_chembl_id,target_organism,target_pref_name,target_tax_id,text_value,toid,type,units,uo_units,upper_value,value
,,316960,[],CHEMBL766864,Inhibition of Protein kinase B (AKT) at ATP <Km,B,,,BAO_0000190,BAO_0000224,protein format,COc1cc2c(Nc3ccc(Br)cc3F)ncnc2cc1OCCn1ccnn1,,,CHEMBL1135889,J Med Chem,2002,,CHEMBL281872,ZD-4190 FREE BASE,CHEMBL281872,,0,http://www.openphacts.org/units/Nanomolar,35685,>,1,1,>,,IC50,nM,,20000.0,CHEMBL2111353,Homo sapiens,Serine/threonine-protein kinase AKT,9606,,,IC50,uM,UO_0000065,,20.0
,,328362,[],CHEMBL766865,Inhibition of Protein kinase B (AKT) at ATP <Km,B,,,BAO_0000190,BAO_0000224,protein format,COc1cc2c(Nc3ccc(Br)cc3F)ncnc2cc1OCC1CCN(C)CC1.Cl,,,CHEMBL1135889,J Med Chem,2002,,CHEMBL533849,,CHEMBL24828,,0,http://www.openphacts.org/units/Nanomolar,35684,>,1,1,>,,IC50,nM,,20000.0,CHEMBL2111353,Homo sapiens,Serine/threonine-protein kinase AKT,9606,,,IC50,uM,UO_0000065,,20.0
,,491918,[],CHEMBL709030,Inhibition of Akt phosphorylation in LoVo cells,F,,,BAO_0000190,BAO_0000219,cell-based format,COc1cc2c(Nc3ccc(Oc4ccccc4)cc3)c(C#N)cnc2cc1OCCCN1CCOCC1,,,CHEMBL1146624,Bioorg Med Chem Lett,2003,,CHEMBL414139,,CHEMBL414139,,0,http://www.openphacts.org/units/Nanomolar,192281,>,1,1,>,,IC50,nM,,1000.0,CHEMBL2111353,Homo sapiens,Serine/threonine-protein kinase AKT,9606,,,IC50,nM,UO_0000065,,1000.0
,,507379,[],CHEMBL709030,Inhibition of Akt phosphorylation in LoVo cells,F,,,BAO_0000190,BAO_0000219,cell-based format,COc1cc2c(Nc3ccc(Sc4nccn4C)c(Cl)c3)c(C#N)cnc2cc1OCCCN1CCOCC1,,,CHEMBL1146624,Bioorg Med Chem Lett,2003,,CHEMBL318804,,CHEMBL318804,,0,http://www.openphacts.org/units/Nanomolar,192274,>,1,1,>,,IC50,nM,,1000.0,CHEMBL2111353,Homo sapiens,Serine/threonine-protein kinase AKT,9606,,,IC50,nM,UO_0000065,,1000.0
,,634491,[],CHEMBL766867,Inhibition of Akt (proto-oncogenic serine/threonine PKB) kinase,B,,,BAO_0000190,BAO_0000224,protein format,CCCCCCCCCCCCCCCCCCOC[C@H](COP(=O)(O)O[C@H]1[C@@H](O)[C@@H](O)[C@H](O)C[C@H]1O)OC,,,CHEMBL1133107,J Med Chem,2000,"{'bei': '9.96', 'le': '0.20', 'lle': '1.19', 'sei': '3.75'}",CHEMBL2368948,,CHEMBL2368948,5.82,0,http://www.openphacts.org/units/Nanomolar,193335,=,1,1,=,,IC50,nM,,1500.0,CHEMBL2111353,Homo sapiens,Serine/threonine-protein kinase AKT,9606,,,IC50,uM,UO_0000065,,1.5
,,634496,[],CHEMBL766867,Inhibition of Akt (proto-oncogenic serine/threonine PKB) kinase,B,,,BAO_0000190,BAO_0000224,protein format,CCCCCCCCCCCCCCCCCCOC[C@H](COP(=O)(O)O[C@@H]1[C@H](O)[C@H](CO)[C@@H](O)[C@H](O)[C@@H]1O)OC,,,CHEMBL1133107,J Med Chem,2000,"{'bei': '8.31', 'le': '0.17', 'lle': '1.26', 'sei': '2.91'}",CHEMBL2367875,,CHEMBL2367875,5.11,0,http://www.openphacts.org/units/Nanomolar,193340,=,1,1,=,,IC50,nM,,7800.0,CHEMBL2111353,Homo sapiens,Serine/threonine-protein kinase AKT,9606,,,IC50,uM,UO_0000065,,7.8
,,654811,[],CHEMBL766867,Inhibition of Akt (proto-oncogenic serine/threonine PKB) kinase,B,,,BAO_0000190,BAO_0000224,protein format,CCCCCCCCCCCCCCCCCCOC[C@H](COC(=O)O[C@@H]1[C@H](O)[C@H](CO)[C@@H](O)[C@H](O)[C@@H]1O)OC,,,CHEMBL1133107,J Med Chem,2000,"{'bei': '9.16', 'le': '0.18', 'lle': '1.43', 'sei': '3.42'}",CHEMBL2367874,,CHEMBL2367874,5.30,0,http://www.openphacts.org/units/Nanomolar,193336,=,1,1,=,,IC50,nM,,5000.0,CHEMBL2111353,Homo sapiens,Serine/threonine-protein kinase AKT,9606,,,IC50,uM,UO_0000065,,5.0
,,663463,[],CHEMBL766867,Inhibition of Akt (proto-oncogenic serine/threonine PKB) kinase,B,,,BAO_0000190,BAO_0000224,protein format,CCCCCCCCCCCCCCCCCCOC[C@H](COC(=O)O[C@@H]1[C@H](O)[C@@H](CO)[C@@H](O)[C@H](O)[C@@H]1O)OC,,,CHEMBL1133107,J Med Chem,2000,"{'bei': '7.77', 'le': '0.15', 'lle': '0.62', 'sei': '2.90'}",CHEMBL2368953,,CHEMBL2368953,4.50,0,http://www.openphacts.org/units/Nanomolar,193339,=,1,1,=,,IC50,nM,,32000.0,CHEMBL2111353,Homo sapiens,Serine/threonine-protein kinase AKT,9606,,,IC50,uM,UO_0000065,,32.0
,,668670,[],CHEMBL766867,Inhibition of Akt (proto-oncogenic serine/threonine PKB) kinase,B,,,BAO_0000190,BAO_0000224,protein format,CCCCCCCCCCCCCCCCCCOC[C@H](COC(=O)O[C@H]1[C@@H](O)[C@@H](O)[C@H](O)C[C@H]1O)OC,,,CHEMBL1133107,J Med Chem,2000,"{'bei': '8.93', 'le': '0.18', 'lle': '0.25', 'sei': '3.63'}",CHEMBL2367876,,CHEMBL2367876,4.90,0,http://www.openphacts.org/units/Nanomolar,193337,=,1,1,=,,IC50,nM,,12500.0,CHEMBL2111353,Homo sapiens,Serine/threonine-protein kinase AKT,9606,,,IC50,uM,UO_0000065,,12.5

## **Handling missing data**
If any compounds has missing value for the **standard_value** column then drop it

In [ ]:
df2 = df[df.standard_value.notna()]
df2

,action_type,activity_comment,activity_id,activity_properties,assay_chembl_id,assay_description,assay_type,assay_variant_accession,assay_variant_mutation,bao_endpoint,...,target_organism,target_pref_name,target_tax_id,text_value,toid,type,units,uo_units,upper_value,value
0,None,None,316960,[],CHEMBL766864,Inhibition of Protein kinase B (AKT) at ATP <Km,B,None,None,BAO_0000190,...,Homo sapiens,Serine/threonine-protein kinase AKT,9606,None,None,IC50,uM,UO_0000065,None,20.0
1,None,None,328362,[],CHEMBL766865,Inhibition of Protein kinase B (AKT) at ATP <Km,B,None,None,BAO_0000190,...,Homo sapiens,Serine/threonine-protein kinase AKT,9606,None,None,IC50,uM,UO_0000065,None,20.0
2,None,None,491918,[],CHEMBL709030,Inhibition of Akt phosphorylation in LoVo cells,F,None,None,BAO_0000190,...,Homo sapiens,Serine/threonine-protein kinase AKT,9606,None,None,IC50,nM,UO_0000065,None,1000.0
3,None,None,507379,[],CHEMBL709030,Inhibition of Akt phosphorylation in LoVo cells,F,None,None,BAO_0000190,...,Homo sapiens,Serine/threonine-protein kinase AKT,9606,None,None,IC50,nM,UO_0000065,None,1000.0
4,None,None,634491,[],CHEMBL766867,Inhibition of Akt (proto-oncogenic serine/thre...,B,None,None,BAO_0000190,...,Homo sapiens,Serine/threonine-protein kinase AKT,9606,None,None,IC50,uM,UO_0000065,None,1.5
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
151,"{'action_type': 'INHIBITOR', 'description': 'N...",None,26329944,"[{'comments': None, 'relation': '=', 'result_f...",CHEMBL5719503,Inhibition of AKT in human bortezomib-resistan...,B,None,None,BAO_0000190,...,Homo sapiens,Serine/threonine-protein kinase AKT,9606,None,None,IC50,nM,UO_0000065,None,10000.0
152,"{'action_type': 'INHIBITOR', 'description': 'N...",None,26330098,"[{'comments': None, 'relation': '=', 'result_f...",CHEMBL5719596,Inhibition of AKT in human U-266 cells assesse...,B,None,None,BAO_0000190,...,Homo sapiens,Serine/threonine-protein kinase AKT,9606,None,None,IC50,nM,UO_0000065,None,2834.9
153,"{'action_type': 'INHIBITOR', 'description': 'N...",None,26330099,"[{'comments': None, 'relation': '=', 'result_f...",CHEMBL5719596,Inhibition of AKT in human U-266 cells assesse...,B,None,None,BAO_0000190,...,Homo sapiens,Serine/threonine-protein kinase AKT,9606,None,None,IC50,nM,UO_0000065,None,3236.9
154,"{'action_type': 'INHIBITOR', 'description': 'N...",None,26330100,"[{'comments': None, 'relation': '=', 'result_f...",CHEMBL5719596,Inhibition of AKT in human U-266 cells assesse...,B,None,None,BAO_0000190,...,Homo sapiens,Serine/threonine-protein kinase AKT,9606,None,None,IC50,nM,UO_0000065,None,10000.0
155,"{'action_type': 'INHIBITOR', 'description': 'N...",None,26330101,"[{'comments': None, 'relation': '=', 'result_f...",CHEMBL5719596,Inhibition of AKT in human U-266 cells assesse...,B,None,None,BAO_0000190,...,Homo sapiens,Serine/threonine-protein kinase AKT,9606,None,None,IC50,nM,UO_0000065,None,10000.0

Apparently, for this dataset there is no missing data. But we can use the above code cell for bioactivity data of other target protein.

## **Data pre-processing of the bioactivity data**

### **Labeling compounds as either being active, inactive or intermediate**
The bioactivity data is in the IC50 unit. Compounds having values of less than 1000 nM will be considered to be **active** while those greater than 10,000 nM will be considered to be **inactive**. As for those values in between 1,000 and 10,000 nM will be referred to as **intermediate**.

In [ ]:
bioactivity_class = []
for i in df2.standard_value:
  if float(i) >= 10000:
    bioactivity_class.append("inactive")
  elif float(i) <= 1000:
    bioactivity_class.append("active")
  else:
    bioactivity_class.append("intermediate")

### **Iterate the *molecule_chembl_id* to a list**

In [ ]:
mol_cid = []
for i in df2.molecule_chembl_id:
  mol_cid.append(i)

### **Iterate *canonical_smiles* to a list**

In [ ]:
canonical_smiles = []
for i in df2.canonical_smiles:
  canonical_smiles.append(i)

### **Iterate *standard_value* to a list**

In [ ]:
standard_value = []
for i in df2.standard_value:
  standard_value.append(i)

### **Combine the 4 lists into a dataframe**

In [ ]:
data_tuples = list(zip(mol_cid, canonical_smiles, bioactivity_class, standard_value))
df3 = pd.DataFrame( data_tuples,  columns=['molecule_chembl_id', 'canonical_smiles', 'bioactivity_class', 'standard_value'])

In [ ]:
df3

,molecule_chembl_id,canonical_smiles,bioactivity_class,standard_value
0,CHEMBL281872,COc1cc2c(Nc3ccc(Br)cc3F)ncnc2cc1OCCn1ccnn1,inactive,20000.0
1,CHEMBL533849,COc1cc2c(Nc3ccc(Br)cc3F)ncnc2cc1OCC1CCN(C)CC1.Cl,inactive,20000.0
2,CHEMBL414139,COc1cc2c(Nc3ccc(Oc4ccccc4)cc3)c(C#N)cnc2cc1OCC...,active,1000.0
3,CHEMBL318804,COc1cc2c(Nc3ccc(Sc4nccn4C)c(Cl)c3)c(C#N)cnc2cc...,active,1000.0
4,CHEMBL2368948,CCCCCCCCCCCCCCCCCCOC[C@H](COP(=O)(O)O[C@H]1[C@...,intermediate,1500.0
...,...,...,...,...
150,CHEMBL595583,CCCCCCCCCCCCc1ccc(S(=O)(=O)Nc2nncs2)cc1,inactive,10000.0
151,CHEMBL1186409,CC[n+]1c(/C=C/N(C)c2ccccc2)n(-c2ccccc2)c2ccc(-...,intermediate,2834.9
152,CHEMBL379218,Cc1n[nH]c2ccc(-c3cncc(OC[C@@H](N)Cc4ccccc4)c3)...,intermediate,3236.9
153,CHEMBL494089,CCn1c(-c2nonc2N)nc2c(C#CC(C)(C)O)ncc(OC[C@H]3C...,inactive,10000.0
154,CHEMBL595583,CCCCCCCCCCCCc1ccc(S(=O)(=O)Nc2nncs2)cc1,inactive,10000.0

### **Alternative method**

In [ ]:
selection = ['molecule_chembl_id', 'canonical_smiles', 'standard_value']
df3 = df2[selection]
df3

,molecule_chembl_id,canonical_smiles,standard_value
0,CHEMBL281872,COc1cc2c(Nc3ccc(Br)cc3F)ncnc2cc1OCCn1ccnn1,20000.0
1,CHEMBL533849,COc1cc2c(Nc3ccc(Br)cc3F)ncnc2cc1OCC1CCN(C)CC1.Cl,20000.0
2,CHEMBL414139,COc1cc2c(Nc3ccc(Oc4ccccc4)cc3)c(C#N)cnc2cc1OCC...,1000.0
3,CHEMBL318804,COc1cc2c(Nc3ccc(Sc4nccn4C)c(Cl)c3)c(C#N)cnc2cc...,1000.0
4,CHEMBL2368948,CCCCCCCCCCCCCCCCCCOC[C@H](COP(=O)(O)O[C@H]1[C@...,1500.0
...,...,...,...
151,CHEMBL595583,CCCCCCCCCCCCc1ccc(S(=O)(=O)Nc2nncs2)cc1,10000.0
152,CHEMBL1186409,CC[n+]1c(/C=C/N(C)c2ccccc2)n(-c2ccccc2)c2ccc(-...,2834.9
153,CHEMBL379218,Cc1n[nH]c2ccc(-c3cncc(OC[C@@H](N)Cc4ccccc4)c3)...,3236.9
154,CHEMBL494089,CCn1c(-c2nonc2N)nc2c(C#CC(C)(C)O)ncc(OC[C@H]3C...,10000.0
155,CHEMBL595583,CCCCCCCCCCCCc1ccc(S(=O)(=O)Nc2nncs2)cc1,10000.0

In [ ]:
pd.concat([df3,pd.Series(bioactivity_class)], axis=1)

,molecule_chembl_id,canonical_smiles,standard_value,0
0,CHEMBL281872,COc1cc2c(Nc3ccc(Br)cc3F)ncnc2cc1OCCn1ccnn1,20000.0,inactive
1,CHEMBL533849,COc1cc2c(Nc3ccc(Br)cc3F)ncnc2cc1OCC1CCN(C)CC1.Cl,20000.0,inactive
2,CHEMBL414139,COc1cc2c(Nc3ccc(Oc4ccccc4)cc3)c(C#N)cnc2cc1OCC...,1000.0,active
3,CHEMBL318804,COc1cc2c(Nc3ccc(Sc4nccn4C)c(Cl)c3)c(C#N)cnc2cc...,1000.0,active
4,CHEMBL2368948,CCCCCCCCCCCCCCCCCCOC[C@H](COP(=O)(O)O[C@H]1[C@...,1500.0,intermediate
...,...,...,...,...
152,CHEMBL1186409,CC[n+]1c(/C=C/N(C)c2ccccc2)n(-c2ccccc2)c2ccc(-...,2834.9,intermediate
153,CHEMBL379218,Cc1n[nH]c2ccc(-c3cncc(OC[C@@H](N)Cc4ccccc4)c3)...,3236.9,inactive
154,CHEMBL494089,CCn1c(-c2nonc2N)nc2c(C#CC(C)(C)O)ncc(OC[C@H]3C...,10000.0,inactive
155,CHEMBL595583,CCCCCCCCCCCCc1ccc(S(=O)(=O)Nc2nncs2)cc1,10000.0,NaN
29,NaN,NaN,NaN,intermediate

Saves dataframe to CSV file

In [ ]:
df3.to_csv('bioactivity_preprocessed_data.csv', index=False)

In [ ]:
! ls -l

total 144
-rw-r--r-- 1 root root 122535 Mar 20 07:17 bioactivity_data.csv
-rw-r--r-- 1 root root  13019 Mar 20 07:22 bioactivity_preprocessed_data.csv
drwx------ 5 root root   4096 Mar 20 07:18 gdrive
drwxr-xr-x 1 root root   4096 Mar 17 17:58 sample_data

Let's copy to the Google Drive

In [ ]:
import os

dest_dir = "/content/gdrive/MyDrive/Colab Notebooks/QSAR MODELLING CODES/AKT1"

# Copy bioactivity_data.csv
! cp bioactivity_data.csv "{dest_dir}"

# Copy bioactivity_preprocessed_data.csv
! cp bioactivity_preprocessed_data.csv "{dest_dir}"

In [ ]:
# Verify the files are copied
! ls -l "/content/gdrive/MyDrive/Colab Notebooks/QSAR MODELLING CODES/AKT1"

total 133
-rw------- 1 root root 122535 Mar 20 10:31 bioactivity_data.csv
-rw------- 1 root root  13019 Mar 20 10:31 bioactivity_preprocessed_data.csv

---