<a href="https://colab.research.google.com/github/FasikuChristian/QSAR-Modeling-Pipeline-for-Serine-Threonine-Kinase-1/blob/main/CDD_ML_Part_3_QSAR_Descriptor_Dataset_Preparation_refined.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

# **Bioinformatics Project - Computational Drug Discovery  3 Descriptor Calculation and Dataset Preparation**
Credits: Chanin Nantasenamat(Data Professor) for developing this pipeline

## **Download PaDEL-Descriptor**

In [ ]:
!wget https://clowder.edap-cluster.com/api/files/6321db62e4b04f6bb1348ccf

--2026-03-20 12:28:39--  https://clowder.edap-cluster.com/api/files/6321db62e4b04f6bb1348ccf
Resolving clowder.edap-cluster.com (clowder.edap-cluster.com)... 52.201.128.100, 54.205.66.212
Connecting to clowder.edap-cluster.com (clowder.edap-cluster.com)|52.201.128.100|:443... connected.
HTTP request sent, awaiting response... 200 OK
Length: unspecified [multi/files-zipped]
Saving to: ‘6321db62e4b04f6bb1348ccf’

6321db62e4b04f6bb13     [       <=>          ]  19.91M  8.23MB/s    in 2.4s

2026-03-20 12:28:43 (8.23 MB/s) - ‘6321db62e4b04f6bb1348ccf’ saved [20875190]

In [ ]:
!unzip 6321db62e4b04f6bb1348ccf -d padel

Archive:  6321db62e4b04f6bb1348ccf
  inflating: padel/Descriptors.xls
  inflating: padel/descriptors.xml
   creating: padel/lib/
  inflating: padel/lib/ambit2-base-2.4.7-SNAPSHOT.jar
  inflating: padel/lib/ambit2-core-2.4.7-SNAPSHOT.jar
  inflating: padel/lib/ambit2-smarts-2.4.7-SNAPSHOT.jar
  inflating: padel/lib/appframework-1.0.3.jar
  inflating: padel/lib/cdk-1.4.15.jar
  inflating: padel/lib/commons-cli-1.2.jar
  inflating: padel/lib/guava-17.0.jar
  inflating: padel/lib/jama.jar
  inflating: padel/lib/jgrapht-0.6.0.jar
  inflating: padel/lib/l2fprod-common-all.jar
  inflating: padel/lib/libPaDEL-Descriptor.jar
  inflating: padel/lib/libPaDEL-Jobs.jar
  inflating: padel/lib/libPaDEL.jar
  inflating: padel/lib/swing-worker-1.1.jar
  inflating: padel/lib/vecmath1.2-1.14.jar
  inflating: padel/lib/xom-1.1.jar
   creating: padel/license/
  inflating: padel/license/lgpl-2.1.txt
  inflating: padel/license/lgpl.license
  inflating: padel/license/LICENSE.txt
  inflating: padel/license/README - CDK
  inflating: padel/PaDEL-Descriptor.jar

In [ ]:
from google.colab import drive
drive.mount('/content/drive')

Mounted at /content/drive

## **Load bioactivity data**

Download the curated ChEMBL bioactivity data that has been pre-processed from Parts 1 and 2 of this Bioinformatics Project series. Here we will be using the **bioactivity_data_3class_pIC50.csv** file that essentially contain the pIC50 values that we will be using for building a regression model.

##Load data with all entries

In [ ]:
import pandas as pd
df3 = pd.read_csv('/content/drive/MyDrive/Colab Notebooks/QSAR MODELLING CODES/AKT1/AKT1_04_bioactivity_data_3class_pIC50_all.csv')

In [ ]:
df3

,Unnamed: 0,molecule_chembl_id,canonical_smiles,class,MW,LogP,NumHDonors,NumHAcceptors,pIC50
0,0,CHEMBL281872,COc1cc2c(Nc3ccc(Br)cc3F)ncnc2cc1OCCn1ccnn1,inactive,459.279,3.95410,1.0,8.0,4.698970
1,1,CHEMBL533849,COc1cc2c(Nc3ccc(Br)cc3F)ncnc2cc1OCC1CCN(C)CC1.Cl,inactive,475.362,5.00420,1.0,6.0,4.698970
2,2,CHEMBL414139,COc1cc2c(Nc3ccc(Oc4ccccc4)cc3)c(C#N)cnc2cc1OCC...,active,510.594,5.75208,1.0,8.0,6.000000
3,3,CHEMBL318804,COc1cc2c(Nc3ccc(Sc4nccn4C)c(Cl)c3)c(C#N)cnc2cc...,active,565.099,5.49788,1.0,10.0,6.000000
4,4,CHEMBL2368948,CCCCCCCCCCCCCCCCCCOC[C@H](COP(=O)(O)O[C@H]1[C@...,intermediate,584.728,4.62900,5.0,9.0,5.823909
...,...,...,...,...,...,...,...,...,...
150,150,CHEMBL595583,CCCCCCCCCCCCc1ccc(S(=O)(=O)Nc2nncs2)cc1,inactive,409.621,5.80230,1.0,5.0,5.000000
151,151,CHEMBL1186409,CC[n+]1c(/C=C/N(C)c2ccccc2)n(-c2ccccc2)c2ccc(-...,intermediate,487.652,7.32170,0.0,4.0,5.547462
152,152,CHEMBL379218,Cc1n[nH]c2ccc(-c3cncc(OC[C@@H](N)Cc4ccccc4)c3)...,intermediate,358.445,3.88212,2.0,4.0,5.489871
153,153,CHEMBL494089,CCn1c(-c2nonc2N)nc2c(C#CC(C)(C)O)ncc(OC[C@H]3C...,inactive,425.493,1.58420,3.0,10.0,5.000000
154,154,CHEMBL595583,CCCCCCCCCCCCc1ccc(S(=O)(=O)Nc2nncs2)cc1,inactive,409.621,5.80230,1.0,5.0,5.000000

In [ ]:
selection = ['canonical_smiles','molecule_chembl_id']
df3_selection = df3[selection]
df3_selection.to_csv('molecule.smi', sep='\t', index=False, header=False)

In [ ]:
! cat molecule.smi | head -5

COc1cc2c(Nc3ccc(Br)cc3F)ncnc2cc1OCCn1ccnn1	CHEMBL281872
COc1cc2c(Nc3ccc(Br)cc3F)ncnc2cc1OCC1CCN(C)CC1.Cl	CHEMBL533849
COc1cc2c(Nc3ccc(Oc4ccccc4)cc3)c(C#N)cnc2cc1OCCCN1CCOCC1	CHEMBL414139
COc1cc2c(Nc3ccc(Sc4nccn4C)c(Cl)c3)c(C#N)cnc2cc1OCCCN1CCOCC1	CHEMBL318804
CCCCCCCCCCCCCCCCCCOC[C@H](COP(=O)(O)O[C@H]1[C@@H](O)[C@@H](O)[C@H](O)C[C@H]1O)OC	CHEMBL2368948

In [ ]:
! cat molecule.smi | wc -l

155

## **Calculate fingerprint descriptors**

### **Calculate PaDEL descriptors**

In [ ]:
! cat padel.sh

java -Xms1G -Xmx1G -Djava.awt.headless=true -jar ./padel/PaDEL-Descriptor.jar -removesalt -standardizenitro -fingerprints -descriptortypes ./padel/descriptors.xml -maxcpd 0 -threads 4 -dir molecule.smi -file descriptors_output.csv

In [ ]:
! bash padel.sh

Mar 20, 2026 1:03:46 PM padeldescriptor.PaDELDescriptorApp launchCommandLine
WARNING: Unrecognized option: -maxcpd

In [ ]:
%%writefile padel.sh
java -Xms1G -Xmx1G -Djava.awt.headless=true -jar ./padel/PaDEL-Descriptor.jar -removesalt -standardizenitro -fingerprints -descriptortypes ./padel/descriptors.xml -threads 4 -dir molecule.smi -file descriptors_output.csv

Overwriting padel.sh

In [ ]:
! bash padel.sh

Processing CHEMBL318804 in molecule.smi (4/155).
Processing CHEMBL533849 in molecule.smi (2/155).
Processing CHEMBL414139 in molecule.smi (3/155).
Processing CHEMBL281872 in molecule.smi (1/155).
Processing CHEMBL2367875 in molecule.smi (6/155). Average speed: 2.91 s/mol.
Processing CHEMBL2368948 in molecule.smi (5/155). Average speed: 2.83 s/mol.
Processing CHEMBL2367874 in molecule.smi (7/155). Average speed: 0.99 s/mol.
Processing CHEMBL2368953 in molecule.smi (8/155). Average speed: 0.84 s/mol.
Processing CHEMBL2367876 in molecule.smi (9/155). Average speed: 0.93 s/mol.
Processing CHEMBL2368947 in molecule.smi (10/155). Average speed: 0.75 s/mol.
Processing CHEMBL2368954 in molecule.smi (11/155). Average speed: 0.55 s/mol.
Processing CHEMBL2368946 in molecule.smi (12/155). Average speed: 0.59 s/mol.
Processing CHEMBL2368953 in molecule.smi (13/155). Average speed: 0.50 s/mol.
Processing CHEMBL2368944 in molecule.smi (14/155). Average speed: 0.46 s/mol.
Processing CHEMBL2368947 in molecule.smi (15/155). Average speed: 0.47 s/mol.
Processing CHEMBL2368948 in molecule.smi (16/155). Average speed: 0.43 s/mol.
Processing CHEMBL2368945 in molecule.smi (17/155). Average speed: 0.41 s/mol.
Processing CHEMBL536718 in molecule.smi (18/155). Average speed: 0.41 s/mol.
Processing CHEMBL536485 in molecule.smi (19/155). Average speed: 0.38 s/mol.
Processing CHEMBL554986 in molecule.smi (20/155). Average speed: 0.38 s/mol.
Processing CHEMBL534916 in molecule.smi (21/155). Average speed: 0.37 s/mol.
Processing CHEMBL537180 in molecule.smi (22/155). Average speed: 0.34 s/mol.
Processing CHEMBL365847 in molecule.smi (23/155). Average speed: 0.34 s/mol.
Processing CHEMBL373101 in molecule.smi (24/155). Average speed: 0.33 s/mol.
Processing CHEMBL383172 in molecule.smi (25/155). Average speed: 0.34 s/mol.
Processing CHEMBL195029 in molecule.smi (26/155). Average speed: 0.32 s/mol.
Processing CHEMBL377734 in molecule.smi (27/155). Average speed: 0.31 s/mol.
Processing CHEMBL5416410 in molecule.smi (28/155). Average speed: 0.30 s/mol.
Processing CHEMBL228133 in molecule.smi (29/155). Average speed: 0.30 s/mol.
Processing CHEMBL228133 in molecule.smi (30/155). Average speed: 0.30 s/mol.
Processing CHEMBL242753 in molecule.smi (31/155). Average speed: 0.28 s/mol.
Processing CHEMBL438485 in molecule.smi (32/155). Average speed: 0.28 s/mol.
Processing CHEMBL3922916 in molecule.smi (33/155). Average speed: 0.27 s/mol.
Processing CHEMBL3544960 in molecule.smi (34/155). Average speed: 0.27 s/mol.
Processing CHEMBL3942454 in molecule.smi (35/155). Average speed: 0.27 s/mol.
Processing CHEMBL3544960 in molecule.smi (36/155). Average speed: 0.27 s/mol.
Processing CHEMBL3942454 in molecule.smi (37/155). Average speed: 0.27 s/mol.
Processing CHEMBL4440965 in molecule.smi (38/155). Average speed: 0.26 s/mol.
Processing CHEMBL4457064 in molecule.smi (39/155). Average speed: 0.26 s/mol.
Processing CHEMBL4792262 in molecule.smi (40/155). Average speed: 0.26 s/mol.
Processing CHEMBL4788683 in molecule.smi (41/155). Average speed: 0.25 s/mol.
Processing CHEMBL4780030 in molecule.smi (42/155). Average speed: 0.25 s/mol.
Processing CHEMBL388978 in molecule.smi (43/155). Average speed: 0.25 s/mol.
Processing CHEMBL3890900 in molecule.smi (44/155). Average speed: 0.25 s/mol.
Processing CHEMBL3920854 in molecule.smi (45/155). Average speed: 0.25 s/mol.
Processing CHEMBL3982464 in molecule.smi (46/155). Average speed: 0.25 s/mol.
Processing CHEMBL3935218 in molecule.smi (47/155). Average speed: 0.25 s/mol.
Processing CHEMBL3928625 in molecule.smi (48/155). Average speed: 0.24 s/mol.
Processing CHEMBL3948645 in molecule.smi (49/155). Average speed: 0.25 s/mol.
Processing CHEMBL3919663 in molecule.smi (50/155). Average speed: 0.25 s/mol.
Processing CHEMBL3964789 in molecule.smi (51/155). Average speed: 0.24 s/mol.
Processing CHEMBL3941307 in molecule.smi (52/155). Average speed: 0.25 s/mol.
Processing CHEMBL3964726 in molecule.smi (53/155). Average speed: 0.24 s/mol.
Processing CHEMBL3922417 in molecule.smi (54/155). Average speed: 0.24 s/mol.
Processing CHEMBL3978717 in molecule.smi (55/155). Average speed: 0.24 s/mol.
Processing CHEMBL3929608 in molecule.smi (56/155). Average speed: 0.24 s/mol.
Processing CHEMBL3935451 in molecule.smi (57/155). Average speed: 0.23 s/mol.
Processing CHEMBL3925871 in molecule.smi (59/155). Average speed: 0.23 s/mol.
Processing CHEMBL3912964 in molecule.smi (58/155). Average speed: 0.24 s/mol.
Processing CHEMBL3933645 in molecule.smi (60/155). Average speed: 0.23 s/mol.
Processing CHEMBL3903522 in molecule.smi (61/155). Average speed: 0.23 s/mol.
Processing CHEMBL3916957 in molecule.smi (62/155). Average speed: 0.23 s/mol.
Processing CHEMBL3932445 in molecule.smi (63/155). Average speed: 0.23 s/mol.
Processing CHEMBL3916864 in molecule.smi (64/155). Average speed: 0.23 s/mol.
Processing CHEMBL3936329 in molecule.smi (65/155). Average speed: 0.22 s/mol.
Processing CHEMBL3931848 in molecule.smi (66/155). Average speed: 0.23 s/mol.
Processing CHEMBL3911401 in molecule.smi (67/155). Average speed: 0.22 s/mol.
Processing CHEMBL3919089 in molecule.smi (69/155). Average speed: 0.22 s/mol.
Processing CHEMBL3900512 in molecule.smi (68/155). Average speed: 0.22 s/mol.
Processing CHEMBL3931504 in molecule.smi (70/155). Average speed: 0.22 s/mol.
Processing CHEMBL3922798 in molecule.smi (71/155). Average speed: 0.22 s/mol.
Processing CHEMBL3962807 in molecule.smi (73/155). Average speed: 0.22 s/mol.
Processing CHEMBL4876889 in molecule.smi (72/155). Average speed: 0.22 s/mol.
Processing CHEMBL3917410 in molecule.smi (74/155). Average speed: 0.21 s/mol.
Processing CHEMBL3949501 in molecule.smi (75/155). Average speed: 0.21 s/mol.
Processing CHEMBL4853207 in molecule.smi (76/155). Average speed: 0.21 s/mol.
Processing CHEMBL4795065 in molecule.smi (78/155). Average speed: 0.21 s/mol.
Processing CHEMBL4297188 in molecule.smi (77/155). Average speed: 0.21 s/mol.
Processing CHEMBL5281874 in molecule.smi (79/155). Average speed: 0.21 s/mol.
Processing CHEMBL5270720 in molecule.smi (80/155). Average speed: 0.20 s/mol.
Processing CHEMBL5269374 in molecule.smi (81/155). Average speed: 0.20 s/mol.
Processing CHEMBL5419204 in molecule.smi (82/155). Average speed: 0.20 s/mol.
Processing CHEMBL5404456 in molecule.smi (83/155). Average speed: 0.20 s/mol.
Processing CHEMBL5436038 in molecule.smi (84/155). Average speed: 0.20 s/mol.
Processing CHEMBL5423227 in molecule.smi (85/155). Average speed: 0.20 s/mol.
Processing CHEMBL5440814 in molecule.smi (86/155). Average speed: 0.20 s/mol.
Processing CHEMBL5401780 in molecule.smi (87/155). Average speed: 0.20 s/mol.
Processing CHEMBL5426352 in molecule.smi (88/155). Average speed: 0.20 s/mol.
Processing CHEMBL5414256 in molecule.smi (89/155). Average speed: 0.20 s/mol.
Processing CHEMBL5424735 in molecule.smi (90/155). Average speed: 0.19 s/mol.
Processing CHEMBL5394975 in molecule.smi (91/155). Average speed: 0.20 s/mol.
Processing CHEMBL5411976 in molecule.smi (92/155). Average speed: 0.19 s/mol.
Processing CHEMBL5406950 in molecule.smi (93/155). Average speed: 0.19 s/mol.
Processing CHEMBL5402470 in molecule.smi (94/155). Average speed: 0.19 s/mol.
Processing CHEMBL5424195 in molecule.smi (95/155). Average speed: 0.19 s/mol.
Processing CHEMBL5408522 in molecule.smi (96/155). Average speed: 0.19 s/mol.
Processing CHEMBL5437679 in molecule.smi (97/155). Average speed: 0.19 s/mol.
Processing CHEMBL5413908 in molecule.smi (98/155). Average speed: 0.19 s/mol.
Processing CHEMBL5431134 in molecule.smi (99/155). Average speed: 0.19 s/mol.
Processing CHEMBL5424291 in molecule.smi (100/155). Average speed: 0.19 s/mol.
Processing CHEMBL5422741 in molecule.smi (101/155). Average speed: 0.18 s/mol.
Processing CHEMBL5430524 in molecule.smi (102/155). Average speed: 0.18 s/mol.
Processing CHEMBL5409207 in molecule.smi (103/155). Average speed: 0.18 s/mol.
Processing CHEMBL5406570 in molecule.smi (104/155). Average speed: 0.19 s/mol.
Processing CHEMBL5419204 in molecule.smi (105/155). Average speed: 0.18 s/mol.
Processing CHEMBL5404456 in molecule.smi (106/155). Average speed: 0.18 s/mol.
Processing CHEMBL5436038 in molecule.smi (107/155). Average speed: 0.18 s/mol.
Processing CHEMBL5423227 in molecule.smi (108/155). Average speed: 0.18 s/mol.
Processing CHEMBL5440814 in molecule.smi (109/155). Average speed: 0.18 s/mol.
Processing CHEMBL5401780 in molecule.smi (110/155). Average speed: 0.18 s/mol.
Processing CHEMBL5426352 in molecule.smi (111/155). Average speed: 0.18 s/mol.
Processing CHEMBL5414256 in molecule.smi (112/155). Average speed: 0.18 s/mol.
Processing CHEMBL5424735 in molecule.smi (113/155). Average speed: 0.18 s/mol.
Processing CHEMBL5394975 in molecule.smi (114/155). Average speed: 0.18 s/mol.
Processing CHEMBL5411976 in molecule.smi (115/155). Average speed: 0.18 s/mol.
Processing CHEMBL5406950 in molecule.smi (116/155). Average speed: 0.18 s/mol.
Processing CHEMBL5402470 in molecule.smi (117/155). Average speed: 0.18 s/mol.
Processing CHEMBL5408522 in molecule.smi (119/155). Average speed: 0.17 s/mol.
Processing CHEMBL5424195 in molecule.smi (118/155). Average speed: 0.17 s/mol.
Processing CHEMBL5437679 in molecule.smi (120/155). Average speed: 0.17 s/mol.
Processing CHEMBL5413908 in molecule.smi (121/155). Average speed: 0.17 s/mol.
Processing CHEMBL5431134 in molecule.smi (122/155). Average speed: 0.17 s/mol.
Processing CHEMBL5556059 in molecule.smi (123/155). Average speed: 0.17 s/mol.
Processing CHEMBL2325741 in molecule.smi (124/155). Average speed: 0.17 s/mol.
Processing CHEMBL5612882 in molecule.smi (125/155). Average speed: 0.17 s/mol.
Processing CHEMBL5612418 in molecule.smi (126/155). Average speed: 0.17 s/mol.
Processing CHEMBL5612290 in molecule.smi (127/155). Average speed: 0.17 s/mol.
Processing CHEMBL5612541 in molecule.smi (128/155). Average speed: 0.17 s/mol.
Processing CHEMBL5613746 in molecule.smi (129/155). Average speed: 0.17 s/mol.
Processing CHEMBL5612077 in molecule.smi (130/155). Average speed: 0.17 s/mol.
Processing CHEMBL494089 in molecule.smi (131/155). Average speed: 0.17 s/mol.
Processing CHEMBL1186409 in molecule.smi (132/155). Average speed: 0.17 s/mol.
Processing CHEMBL379218 in molecule.smi (133/155). Average speed: 0.17 s/mol.
Processing CHEMBL494089 in molecule.smi (134/155). Average speed: 0.17 s/mol.
Processing CHEMBL595583 in molecule.smi (135/155). Average speed: 0.17 s/mol.
Processing CHEMBL1186409 in molecule.smi (136/155). Average speed: 0.17 s/mol.
Processing CHEMBL379218 in molecule.smi (137/155). Average speed: 0.17 s/mol.
Processing CHEMBL494089 in molecule.smi (138/155). Average speed: 0.17 s/mol.
Processing CHEMBL595583 in molecule.smi (139/155). Average speed: 0.17 s/mol.
Processing CHEMBL1186409 in molecule.smi (140/155). Average speed: 0.17 s/mol.
Processing CHEMBL379218 in molecule.smi (141/155). Average speed: 0.17 s/mol.
Processing CHEMBL494089 in molecule.smi (142/155). Average speed: 0.17 s/mol.
Processing CHEMBL595583 in molecule.smi (143/155). Average speed: 0.17 s/mol.
Processing CHEMBL1186409 in molecule.smi (144/155). Average speed: 0.17 s/mol.
Processing CHEMBL494089 in molecule.smi (146/155). Average speed: 0.17 s/mol.
Processing CHEMBL379218 in molecule.smi (145/155). Average speed: 0.17 s/mol.
Processing CHEMBL595583 in molecule.smi (147/155). Average speed: 0.17 s/mol.
Processing CHEMBL1186409 in molecule.smi (148/155). Average speed: 0.17 s/mol.
Processing CHEMBL379218 in molecule.smi (149/155). Average speed: 0.17 s/mol.
Processing CHEMBL494089 in molecule.smi (150/155). Average speed: 0.17 s/mol.
Processing CHEMBL595583 in molecule.smi (151/155). Average speed: 0.17 s/mol.
Processing CHEMBL1186409 in molecule.smi (152/155). Average speed: 0.17 s/mol.
Processing CHEMBL379218 in molecule.smi (153/155). Average speed: 0.17 s/mol.
Processing CHEMBL494089 in molecule.smi (154/155). Average speed: 0.17 s/mol.
Processing CHEMBL595583 in molecule.smi (155/155). Average speed: 0.17 s/mol.
Descriptor calculation completed in 25.695 secs . Average speed: 0.17 s/mol.

In [ ]:
! ls -l

total 20700
-rw-r--r-- 1 root root 20875190 Mar 20 12:28 6321db62e4b04f6bb1348ccf
-rw-r--r-- 1 root root   286900 Mar 20 13:04 descriptors_output.csv
drwx------ 5 root root     4096 Mar 20 12:34 drive
-rw-r--r-- 1 root root    11983 Mar 20 12:45 molecule.smi
drwxr-xr-x 4 root root     4096 Mar 20 12:31 padel
-rw-r--r-- 1 root root      221 Mar 20 13:04 padel.sh
drwxr-xr-x 1 root root     4096 Mar 17 17:58 sample_data

## **Preparing the X and Y Data Matrices**

### **X data matrix**

In [ ]:
df3_X = pd.read_csv('descriptors_output.csv')

In [ ]:
df3_X

               Name  PubchemFP0  ...  PubchemFP879  PubchemFP880
0      CHEMBL336398           1  ...             0             0
1      CHEMBL133897           1  ...             0             0
2      CHEMBL130628           1  ...             0             0
3      CHEMBL131588           1  ...             0             0
4      CHEMBL130478           1  ...             0             0
...             ...         ...  ...           ...           ...
4690  CHEMBL4293155           1  ...             0             0
4691  CHEMBL4282558           1  ...             0             0
4692  CHEMBL4281727           1  ...             0             0
4693  CHEMBL4292349           1  ...             0             0
4694  CHEMBL4278260           1  ...             0             0

[4695 rows x 882 columns]

In [ ]:
df3_X = df3_X.drop(columns=['Name'])
df3_X

,PubchemFP0,PubchemFP1,PubchemFP2,PubchemFP3,PubchemFP4,PubchemFP5,PubchemFP6,PubchemFP7,PubchemFP8,PubchemFP9,...,PubchemFP871,PubchemFP872,PubchemFP873,PubchemFP874,PubchemFP875,PubchemFP876,PubchemFP877,PubchemFP878,PubchemFP879,PubchemFP880
0,1,1,1,0,0,0,0,0,0,1,...,0,0,0,0,0,0,0,0,0,0
1,1,1,1,0,0,0,0,0,0,1,...,0,0,0,0,0,0,0,0,0,0
2,1,1,1,0,0,0,0,0,0,1,...,0,0,0,0,0,0,0,0,0,0
3,1,1,1,0,0,0,0,0,0,1,...,0,0,0,0,0,0,0,0,0,0
4,1,1,1,1,0,0,0,0,0,1,...,0,0,0,0,0,0,0,0,0,0
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
150,1,1,1,0,0,0,0,0,0,1,...,0,0,0,0,0,0,0,0,0,0
151,1,1,1,0,0,0,0,0,0,1,...,0,0,0,0,0,0,0,0,0,0
152,1,1,1,0,0,0,0,0,0,1,...,0,0,0,0,0,0,0,0,0,0
153,1,1,1,0,0,0,0,0,0,1,...,0,0,0,0,0,0,0,0,0,0
154,1,1,1,0,0,0,0,0,0,1,...,0,0,0,0,0,0,0,0,0,0

## **Y variable**

### **Convert IC50 to pIC50**

In [ ]:
df3_Y = df3['pIC50']
df3_Y

0      4.698970
1      4.698970
2      6.000000
3      6.000000
4      5.823909
         ...
150    5.000000
151    5.547462
152    5.489871
153    5.000000
154    5.000000
Name: pIC50, Length: 155, dtype: float64

## **Combining X and Y variable**

In [ ]:
dataset3 = pd.concat([df3_X,df3_Y], axis=1)
dataset3

,PubchemFP0,PubchemFP1,PubchemFP2,PubchemFP3,PubchemFP4,PubchemFP5,PubchemFP6,PubchemFP7,PubchemFP8,PubchemFP9,...,PubchemFP872,PubchemFP873,PubchemFP874,PubchemFP875,PubchemFP876,PubchemFP877,PubchemFP878,PubchemFP879,PubchemFP880,pIC50
0,1,1,1,0,0,0,0,0,0,1,...,0,0,0,0,0,0,0,0,0,4.698970
1,1,1,1,0,0,0,0,0,0,1,...,0,0,0,0,0,0,0,0,0,4.698970
2,1,1,1,0,0,0,0,0,0,1,...,0,0,0,0,0,0,0,0,0,6.000000
3,1,1,1,0,0,0,0,0,0,1,...,0,0,0,0,0,0,0,0,0,6.000000
4,1,1,1,1,0,0,0,0,0,1,...,0,0,0,0,0,0,0,0,0,5.823909
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
150,1,1,1,0,0,0,0,0,0,1,...,0,0,0,0,0,0,0,0,0,5.000000
151,1,1,1,0,0,0,0,0,0,1,...,0,0,0,0,0,0,0,0,0,5.547462
152,1,1,1,0,0,0,0,0,0,1,...,0,0,0,0,0,0,0,0,0,5.489871
153,1,1,1,0,0,0,0,0,0,1,...,0,0,0,0,0,0,0,0,0,5.000000
154,1,1,1,0,0,0,0,0,0,1,...,0,0,0,0,0,0,0,0,0,5.000000

In [ ]:
dataset3.to_csv('AKT_06_bioactivity_data_3class_pIC50_pubchem_fp.csv', index=False)

In [ ]:
import os

dest_dir = "/content/drive/MyDrive/Colab Notebooks/QSAR MODELLING CODES/AKT1"

# Copy file
! cp descriptors_output.csv "{dest_dir}"
! cp AKT_06_bioactivity_data_3class_pIC50_pubchem_fp.csv "{dest_dir}"

# **Let's download the CSV file to your local computer for the Part 3B (Model Building).**